# Generated by Django 5.0.6 on 2024-12-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject_detail',
            name='orensemester',
            field=models.IntegerField(default=1),
        ),
    ]
