# Generated by Django 5.0.6 on 2025-04-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_subject_detail_orensemester'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
