# Generated by Django 5.0.6 on 2025-04-30 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_batch_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='section',
        ),
        migrations.CreateModel(
            name='BatchSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=10)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Home.batch')),
            ],
        ),
    ]
