# Generated by Django 5.0.6 on 2025-04-30 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_batch_section_batchsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackres',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.batchsection'),
        ),
    ]
