# Generated by Django 5.0.6 on 2025-05-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_feedbackres_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackres',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
